package com.pathfinder.adaptive;

import com.pathfinder.auth.User;
import com.pathfinder.common.AppException;
import com.pathfinder.common.AuditLogService;
import com.pathfinder.digitaltwin.DigitalTwinEngine;
import com.pathfinder.digitaltwin.DigitalTwinSnapshot;
import com.pathfinder.intelligence.FailureEvent;
import com.pathfinder.intelligence.FailureEventRepository;
import com.pathfinder.learning.*;
import com.pathfinder.profile.ProfileService;
import com.pathfinder.profile.StudentProfile;
import com.pathfinder.skills.Skill;
import com.pathfinder.skills.SkillRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.List;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class AdaptivePlanningEngine {

    private final LearningPlanRepository learningPlanRepository;
    private final RoadmapPhaseRepository phaseRepository;
    private final LearningTaskRepository taskRepository;
    private final AdaptationEventRepository adaptationRepository;
    private final FailureEventRepository failureRepository;
    private final SkillRepository skillRepository;
    private final ProfileService profileService;
    private final DigitalTwinEngine digitalTwinEngine;
    private final AuditLogService auditLogService;

    @Transactional
    public AdaptiveDto.AdaptationResponse adaptOnFailure(User user, Long failureId) {
        StudentProfile profile = profileService.getOrCreateProfile(user);
        FailureEvent failure = failureRepository.findById(failureId)
                .orElseThrow(() -> new AppException("Failure event not found"));

        LearningPlan plan = learningPlanRepository
                .findFirstByStudentProfileIdAndStatusOrderByVersionDesc(profile.getId(), LearningPlan.PlanStatus.ACTIVE)
                .orElseThrow(() -> new AppException("No active learning plan to adapt"));

        Skill weakSkill = failure.getSkill();
        String skillName = weakSkill != null ? weakSkill.getName() : "Foundational Prerequisite";

        String beforeSummary = "Phase 1: Prerequisites -> Phase 2: Core Frameworks & Spring Data JPA -> Phase 3: Capstone";
        String afterSummary = String.format("Phase 1: Prerequisites -> Phase 1.5: Reinforcement (%s Practice & Diagnostics) -> Phase 2: Advanced Topics", skillName);

        // Retrieve current twin version
        int prevTwinVersion = digitalTwinEngine.getCurrentState(user).getCurrentVersion();

        // 1. Insert an adapted reinforcement phase or tasks into the active plan
        RoadmapPhase reinforcementPhase = RoadmapPhase.builder()
                .learningPlan(plan)
                .phaseOrder(2) // Insert right before intermediate topics
                .title("Adaptive Reinforcement: " + skillName + " Mastery & Remediation")
                .description("Targeted remediation generated by the Adaptive Planning Engine in response to " + failure.getContext())
                .durationWeeks(2)
                .status(RoadmapPhase.PhaseStatus.IN_PROGRESS)
                .build();
        RoadmapPhase savedPhase = phaseRepository.save(reinforcementPhase);

        // Add 2 targeted recovery tasks
        LearningTask t1 = LearningTask.builder()
                .roadmapPhase(savedPhase)
                .taskOrder(1)
                .title("Diagnostic Drill: " + skillName + " Edge Cases & Query Optimization")
                .description("Work through targeted exercises addressing failure identified in: " + failure.getContext())
                .skill(weakSkill)
                .difficulty(3)
                .estimatedHours(5.0)
                .priority(LearningTask.TaskPriority.CRITICAL)
                .status(LearningTask.TaskStatus.NOT_STARTED)
                .deadline(Instant.now().plus(4, ChronoUnit.DAYS))
                .build();
        taskRepository.save(t1);

        LearningTask t2 = LearningTask.builder()
                .roadmapPhase(savedPhase)
                .taskOrder(2)
                .title("Remediation Assessment & Practical Verification: " + skillName)
                .description("Retake simulated proficiency test and submit repository proof of mastery.")
                .skill(weakSkill)
                .difficulty(3)
                .estimatedHours(6.0)
                .priority(LearningTask.TaskPriority.HIGH)
                .status(LearningTask.TaskStatus.NOT_STARTED)
                .deadline(Instant.now().plus(8, ChronoUnit.DAYS))
                .build();
        taskRepository.save(t2);

        // Increment plan version
        plan.setVersion(plan.getVersion() + 1);
        learningPlanRepository.save(plan);

        // Mark failure as being addressed
        failure.setIsResolved(true);
        failureRepository.save(failure);

        // Record twin snapshot advancing version
        DigitalTwinSnapshot newSnap = digitalTwinEngine.recordSnapshot(profile, "ADAPTIVE_REPLANNING_EXECUTED",
                String.format("Adaptive replanning triggered by %s failure. Added reinforcement phase for %s.",
                        failure.getContext(), skillName));

        int newTwinVersion = newSnap.getVersion();

        AdaptationEvent adaptation = AdaptationEvent.builder()
                .studentProfile(profile)
                .learningPlan(plan)
                .actionType(AdaptationEvent.ActionType.ADD_PREREQUISITE)
                .triggerReason(String.format("Failed assessment in %s (Score: %.1f%%). Prerequisite reinforcement injected.",
                        failure.getContext(), failure.getScore() != null ? failure.getScore() : 0.0))
                .beforePlanSummary(beforeSummary)
                .afterPlanSummary(afterSummary)
                .previousTwinVersion(prevTwinVersion)
                .newTwinVersion(newTwinVersion)
                .timestamp(Instant.now())
                .build();

        AdaptationEvent savedAdaptation = adaptationRepository.save(adaptation);

        auditLogService.logEvent(
                "ADAPTIVE_PLAN_EXECUTED",
                user.getId(),
                "AdaptationEvent",
                savedAdaptation.getId(),
                String.format("Roadmap adapted. Injected reinforcement phase for %s. Twin advanced v%d -> v%d.",
                        skillName, prevTwinVersion, newTwinVersion)
        );

        return toResponse(savedAdaptation);
    }

    @Transactional(readOnly = true)
    public List<AdaptiveDto.AdaptationResponse> getAdaptationHistory(User user) {
        StudentProfile profile = profileService.getOrCreateProfile(user);
        return adaptationRepository.findByStudentProfileIdOrderByTimestampDesc(profile.getId()).stream()
                .map(this::toResponse)
                .collect(Collectors.toList());
    }

    public AdaptiveDto.AdaptationResponse toResponse(AdaptationEvent a) {
        return AdaptiveDto.AdaptationResponse.builder()
                .id(a.getId())
                .planId(a.getLearningPlan() != null ? a.getLearningPlan().getId() : null)
                .actionType(a.getActionType().name())
                .triggerReason(a.getTriggerReason())
                .beforePlanSummary(a.getBeforePlanSummary())
                .afterPlanSummary(a.getAfterPlanSummary())
                .previousTwinVersion(a.getPreviousTwinVersion())
                .newTwinVersion(a.getNewTwinVersion())
                .timestamp(a.getTimestamp())
                .build();
    }
}
